name: Docker Image CI

on:
  push:
    paths:
      - '*'
      - '!README.md'
      - '!push-tags.sh'
  pull_request:
    paths:
      - '*'
      - '!README.md'
      - '!push-tags.sh'


env:
  SE_VERSION: "4.38"
  SE_REVISION: "9760"
  BUILD_VERSION: "4.38-9760-rtm1"
  SHA256_SUM: "0216a1838ecd841f26ab1a8d34c6f9432e630cee235926b119d6d981a2970afb"


jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Publish to Registry latest
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: wanrenzhizun/softether
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{ env.SE_VERSION }}-latest,${{env.SE_REVISION}}-latest"
          dockerfile: Dockerfile
          buildargs: BUILD_VERSION,SHA256_SUM

      - name: Publish to Registry centos
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: wanrenzhizun/softether
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{env.SE_VERSION}}-centos,${{env.SE_REVISION}}-centos"
          dockerfile: Dockerfile
          buildargs: BUILD_VERSION,SHA256_SUM

      - name: Publish to Registry alpine
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: wanrenzhizun/softether
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{env.SE_VERSION}}-alpine,${{env.SE_REVISION}}-alpine"
          dockerfile: Dockerfile.alpine
          buildargs: BUILD_VERSION,SHA256_SUM

      - name: Publish to Registry debian
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: wanrenzhizun/softether
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{env.SE_VERSION}}-debian,${{env.SE_REVISION}}-debian"
          dockerfile: Dockerfile.debian
          buildargs: BUILD_VERSION,SHA256_SUM

      - name: Publish to Registry ubuntu
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: wanrenzhizun/softether
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "${{env.SE_VERSION}}-ubuntu,${{env.SE_REVISION}}-ubuntu"
          dockerfile: Dockerfile.ubuntu
          buildargs: BUILD_VERSION,SHA256_SUM

